spring.application.name=SmartReview

spring.datasource.url=jdbc:postgresql://localhost:54324/smartreview
spring.datasource.username=sr_admin
spring.datasource.password=sr_admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

smartreview.repo.clone-base-dir=/tmp/smartreview-repos
smartreview.repo.max-file-size-kb=100
smartreview.repo.max-cache-size-gb=5
smartreview.repo.supported-extensions=.java,.py,.ts,.js,.go,.cs,.cpp,.c,.rb,.php

groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.3-70b-versatile

jwt.secret=c67ea205d6c3fb80120bc1cc04d47b70740cbf6ff4ec0bb6066c1d33da817ae1
jwt.expiration=86400000